# Generated by Django 5.1.3 on 2026-06-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_remove_job_company_remove_job_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='current_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='expected_ctc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='present_ctc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
